### ISSUE TITLE
Theming issues Fedora 27

### ISSUE THREAD

**Issue by orschiro** [flathub/com.github.donadigo.appeditor#1]
Hey guys, 

Just tested this on Fedora 27. The theming looks not consistent to me. 

![image](https://user-images.githubusercontent.com/170947/36546171-022b74ee-17eb-11e8-90c4-0d1194c84561.png)

**Comment by TingPing** [comment]
What theme do you use?

**Comment by TingPing** [comment]
Ah same here with Adwaita.

**Comment by orschiro** [comment]
@TingPing yes default Adwaita.

**Comment by TingPing** [comment]
Seems like the theming is very Elementary specific: https://github.com/donadigo/appeditor/blob/master/data/application.css

Should probably ask upstream if they want to support Adwaita or not. If not then the theme will need to be hardcoded.

**Comment by donadigo** [comment]
I do not intend to push fixes for other themes in master. The application was specifically built for elementary OS and it still is, but I don't mind it being here on FlatHub. If you want to patch that out then provide a patch to this repo itself. Removing of loading the application stylesheet should help out: https://github.com/donadigo/appeditor/blob/master/src/MainWindow.vala#L135

**Comment by orschiro** [comment]
@donadigo is this a more generic problem that is applicable to all eOS apps packaged to be potentially packaged for Flatpak?

**Comment by donadigo** [comment]
I don't consider this to be a problem. It's just that those apps target one system - and they look there and behave how they're intented to. It's hard to support every theme out there, and it isn't necessarily only applicable to elementary OS apps, but yes, most apps use custom styling there because 1. it can make your app more recognizable and branding and 2. it's guaranteed that this styling will look right with the elementary stylesheet.

**Comment by mdh34** [comment]
the elementary stylesheet is avaliable on flathub, try installing org.gtk.Gtk3theme.elementary and see if that helps

**Comment by orschiro** [comment]
@mdh34 unfortunately it didn't. Install log below:

```
[orschiro@localhost ~]$ flatpak install flathub org.gtk.Gtk3theme.elementary 
Installing: org.gtk.Gtk3theme.elementary/x86_64/3.22 from flathub
[####################] 1 delta parts, 1 loose fetched; 74 KiB transferred in 1 s
[orschiro@localhost ~]$ 
```

**Comment by TingPing** [comment]
Well we need to bundle it and hardcode it. @donadigo I might consider just hardcoding it upstream personally to avoid any confusion.

**Comment by nedrichards** [comment]
Absolutely agreed @TingPing. I brought this up in the review - but I think this reaction shows I should've pushed harder. Elementary apps need the theme and icons that they expect.

**Comment by donadigo** [comment]
@TingPing what do you mean by hardcoding? I am not sure what you mean.

**Comment by TingPing** [comment]
@donadigo You can override the global theme by setting this property: https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-theme-name

Potentially you could go further and error if not installed but at the very least it allows the application just looking correct as long as the elementary theme is installed without being the global default.

**Comment by donadigo** [comment]
@TingPing can this be just pushed as a patch to the repo here? I would not like to push any FlatHub related things to master.

**Comment by TingPing** [comment]
It isn't flathub related, its every distro not elementary related. But yes it can be kept here.

**Comment by bil-elmoussaoui** [comment]
@TingPing I can push that patch here. Is there a way to make this repo depend on the elementary Gtk theme repository?

**Comment by TingPing** [comment]
@bil-elmoussaoui No, you need to simply install the theme in the package.

**Comment by bil-elmoussaoui** [comment]
Alright, I will prepare a patch. It would be really great to have some basic dependencies logic.

**Comment by TingPing** [comment]
> Alright, I will prepare a patch. It would be really great to have some basic dependencies logic.

It does have basic dependencies. You depend upon one single runtime. Beyond that it tries to avoid becoming a traditional package manager =)

**Comment by bil-elmoussaoui** [comment]
Fixed. The elementary theme is now hardcoded.

**Comment by LeandroStanger** [comment]
This error is happening in Endless OS

[INFO 18:15:17.699178] Application.vala:154: AppEditor version: 0.9.3
[INFO 18:15:17.699283] Application.vala:156: Kernel version: 4.13.0-32-generic
[FATAL 18:15:17.710926] [GLib-GObject] g_object_setv: assertion 'G_IS_OBJECT (object)' failed
[WARNING 18:15:18.862947] [dconf] unable to open file '/var/lib/eos-image-defaults/settings': Falha ao abrir arquivo “/var/lib/eos-image-defaults/settings”: open() falhou: No such file or directory; expect degraded performance
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(com.github.donadigo.appeditor:4): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

**Comment by orschiro** [comment]
I received the following update and this is how it looks like at the moment:

```
[orschiro@localhost ~]$ flatpak update
Looking for updates...
Updating: com.github.donadigo.appeditor/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred 
Now at d5bb0513387a.
```
![image](https://user-images.githubusercontent.com/170947/36584205-08eb2eb2-1879-11e8-95fe-d5f51f1a10bf.png)

**Comment by TingPing** [comment]
I pushed a fix for the patch. @bil-elmoussaoui Please test your commits.

**Comment by orschiro** [comment]
Latest version looks great on Fedora 27 now! Wow! :-D

![image](https://user-images.githubusercontent.com/170947/36590592-729349e2-188f-11e8-96b0-f8018f50cd23.png)
