### ISSUE TITLE
Failed to open file “/var/lib/eos-image-defaults/settings”

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.donadigo.appeditor#5]
[INFO 08:51:55.595479] Application.vala:154: AppEditor version: 0.9.3
[INFO 08:51:55.595627] Application.vala:156: Kernel version: 4.13.0-32-generic
[WARNING 08:51:56.717399] [dconf] unable to open file '/var/lib/eos-image-defaults/settings': Falha ao abrir arquivo “/var/lib/eos-image-defaults/settings”: open() falhou: No such file or directory; expect degraded performance

**Comment by nedrichards** [comment]
Yeah - I don't think this is an issue for anyone else - nor are you missing out on anything important. It's just an artifact of how Endless is put together.
